permalink: /:title/
# Site settings
title: BananPAJ
email: adam@bananpaj.se
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://bananpaj.se" # the base hostname & protocol for your site
twitter_username: tradfursten
github_username:  tradfursten

# Build settings
markdown: redcarpet

redcarpet:
  extensions: ['smart', 'superscript']

gems:
  - jekyll-redirect-from

defaults:
  -
    scope:
      path: ""
    values:
      lang: en
      layout: default
  -
    scope:
      path: _posts/sv
    values:
      lang: sv
  -
    scope:
      path: _posts/sv/pages
    values:
      type: pages
      desc: "Bananpajs sida"
  -
    scope:
      path: _posts/en/pages
    values:
      type: pages
      desc: "Banana pie page"

  -
    scope:
      path: _posts/sv/projects
    values:
      type: projects
  -
    scope:
      path: _posts/en/projects
    values:
      type: projects
